name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Version Packages')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
  
      - name: Setup Node.js lts/Iron
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron

      - name: Enable Corepack
        run: corepack enable
      
      - name: Install the right package manager
        run: corepack install

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create Tags
        run: pnpm changeset tag
      
      - name: Push tags
        run: git push origin --tags

      - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: pnpm publish
  
